#!/usr/bin/env python3
"""Ledger-backed Embry speaker identity policy proof.

This runner migrates the current live memory /speaker/resolve slice into the
canonical Embry event journal shape. It does not prove audio embedding quality:
the candidate evidence is generated by the scenario and is labeled as such.
"""

from __future__ import annotations

import argparse
import json
import time
import uuid
from pathlib import Path
from typing import Any

from embry_event_journal import EventJournal, utc_now
from smoke_embry_intelligence_stress import (
    classify_speaker_resolution,
    post_json,
    speaker_resolution_payload,
)


SCENARIOS: list[dict[str, str]] = [
    {
        "id": "known_horus",
        "matrix_id": "speaker_identity-simple-01",
        "question": "Known Horus asks for personal memory with clean audio.",
    },
    {
        "id": "unknown_speaker",
        "matrix_id": "speaker_identity-simple-02",
        "question": "Unknown speaker asks for Horus memory and must be asked to identify.",
    },
    {
        "id": "ambiguous_low_confidence",
        "matrix_id": "speaker_identity-simple-03",
        "question": "Ambiguous speaker scores must fail closed before recall.",
    },
    {
        "id": "horus_female_overlap",
        "matrix_id": "speaker_identity-simple-04",
        "question": "Female distractor overlaps Horus and must not become memory authority.",
    },
]


def expected_for_scenario(scenario: dict[str, str]) -> dict[str, Any]:
    if scenario["id"] == "known_horus":
        return {
            "status": "known",
            "speaker_id": "horus_lupercal",
            "personal_memory_allowed": True,
            "identity_prompt_required": False,
        }
    if scenario["id"] == "horus_female_overlap":
        return {
            "status": "ambiguous",
            "speaker_id": None,
            "personal_memory_allowed": False,
            "identity_prompt_required": True,
        }
    return {
        "status": "unknown_or_ambiguous",
        "speaker_id": None,
        "personal_memory_allowed": False,
        "identity_prompt_required": True,
    }


def actual_from_resolution(resolution: dict[str, Any]) -> dict[str, Any]:
    payload = resolution.get("json") if isinstance(resolution.get("json"), dict) else {}
    return {
        "status": payload.get("status"),
        "speaker_id": payload.get("speaker_id"),
        "personal_memory_allowed": payload.get("allow_personal_memory"),
        "identity_prompt_present": bool(payload.get("identity_prompt")),
        "memory_tags": payload.get("memory_tags") if isinstance(payload.get("memory_tags"), list) else [],
        "reason": payload.get("reason"),
    }


def run_scenario(
    scenario: dict[str, str],
    *,
    journal: EventJournal,
    memory_url: str,
    timeout_s: int,
) -> dict[str, Any]:
    session = {
        "id": scenario["matrix_id"],
        "route": "memory.speaker.resolve",
        "question": scenario["question"],
    }
    turn_id = scenario["id"]
    journal.append(
        "turn.test.started.v1",
        component="speaker_identity_ledger_runner",
        turn_id=turn_id,
        payload={"scenario": scenario, "expected": expected_for_scenario(scenario)},
        source={
            "live": True,
            "mocked": False,
            "transport": "live_memory_endpoint_with_scenario_candidate_evidence",
            "speaker_evidence_from_audio": False,
        },
    )
    payload = speaker_resolution_payload(session)
    request_event = journal.append(
        "speaker.identity.requested.v1",
        component="speaker_gate",
        turn_id=turn_id,
        payload=payload,
        source={
            "live": True,
            "mocked": False,
            "transport": "live_memory_endpoint_with_scenario_candidate_evidence",
            "speaker_evidence_from_audio": False,
        },
    )
    resolution = post_json(f"{memory_url.rstrip('/')}/speaker/resolve", payload, timeout_s)
    failed = classify_speaker_resolution(session, resolution)
    actual = actual_from_resolution(resolution)
    decision_event = journal.append(
        "speaker.identity.decision.v1",
        component="memory_speaker_resolve",
        turn_id=turn_id,
        parent_event_id=request_event["event_id"],
        payload={
            "scenario_id": scenario["id"],
            "resolution": resolution,
            "actual": actual,
            "failed_gates": failed,
        },
        source={
            "live": bool(resolution.get("ok_http")),
            "mocked": False,
            "transport": "memory_http",
            "speaker_evidence_from_audio": False,
        },
    )
    journal.append(
        "turn.gate.decision.v1",
        component="turn_policy_controller",
        turn_id=turn_id,
        parent_event_id=decision_event["event_id"],
        payload={
            "accepted_state": "accepted_full" if actual["speaker_id"] == "horus_lupercal" else "identity_prompt",
            "personal_memory_allowed": actual["personal_memory_allowed"] is True,
            "reason": actual["reason"],
        },
        source={
            "live": bool(resolution.get("ok_http")),
            "mocked": False,
            "transport": "derived_from_speaker_identity_decision",
            "speaker_evidence_from_audio": False,
        },
    )
    return {
        "id": scenario["id"],
        "matrix_id": scenario["matrix_id"],
        "expected": expected_for_scenario(scenario),
        "actual": actual,
        "ok": not failed,
        "mocked": False,
        "live": bool(resolution.get("ok_http")),
        "speaker_evidence_from_audio": False,
        "failed_gates": failed,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--memory-url", default="http://127.0.0.1:8601")
    parser.add_argument("--timeout-s", default=30, type=int)
    args = parser.parse_args()

    started = time.perf_counter()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    journal = EventJournal(
        out_dir / "events.ndjson",
        session_id=f"speaker-identity-ledger-{uuid.uuid4().hex[:10]}",
        trace_id=f"trace_{uuid.uuid4().hex}",
        repo=Path(__file__).resolve().parents[1],
    )
    journal.append(
        "session.started.v1",
        component="speaker_identity_ledger_runner",
        payload={
            "rung_id": "rung_03_speaker_resolution_policy_ledger",
            "scenario_count": len(SCENARIOS),
            "memory_url": args.memory_url,
            "proof_scope": "live_memory_speaker_resolution_policy_not_audio_identity",
        },
        source={
            "live": True,
            "mocked": False,
            "transport": "runner",
            "speaker_evidence_from_audio": False,
        },
    )

    cases = [run_scenario(scenario, journal=journal, memory_url=args.memory_url, timeout_s=args.timeout_s) for scenario in SCENARIOS]
    failed_gates = [f"{case['id']}:{gate}" for case in cases for gate in case["failed_gates"]]
    if journal.validation_failures:
        failed_gates.extend([f"journal:{gate}" for gate in journal.validation_failures])

    receipt = {
        "schema": "embry.proof.receipt.v1",
        "rung_id": "rung_03_speaker_resolution_policy_ledger",
        "status": "pass" if not failed_gates else "fail",
        "ok": not failed_gates,
        "mocked": False,
        "live": all(case["live"] for case in cases),
        "proof_scope": "live_memory_speaker_resolution_policy_not_audio_identity",
        "source_audio_identity_proven": False,
        "started_at_utc": journal.read_events()[0]["occurred_at"],
        "ended_at_utc": utc_now(),
        "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
        "journal": {
            "path": str(journal.path),
            "sha256": journal.hash(),
            "event_count": len(journal.read_events()),
            "validation_failures": journal.validation_failures,
        },
        "cases": cases,
        "failed_gates": failed_gates,
        "claims": {
            "proves": [
                "live_memory_speaker_resolution_known_unknown_ambiguous_overlap_policy_is_ledgered",
                "speaker_identity_decisions_emit_turn_gate_decisions_with_personal_memory_policy",
            ]
            if not failed_gates
            else [],
            "does_not_prove": [
                "RealtimeSTT_audio_ingress",
                "voice_embedding_correctness",
                "speaker_diarization_correctness",
                "raw_audio_identity_matching",
                "Tau_memory_routing",
                "Chatterbox_speech",
                "Chat_UX_sync",
                "orb_sync",
                "replay",
                "interruption",
            ],
        },
    }
    (out_dir / "receipt.json").write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"ok": receipt["ok"], "live": receipt["live"], "mocked": receipt["mocked"], "receipt": str(out_dir / "receipt.json")}, indent=2))
    return 0 if receipt["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
